### ISSUE TITLE
Trying to load stockfish.js

### ISSUE THREAD

**Issue by shuri** [hi-ogawa/Stockfish#12]
First, thanks for the great repo, project and quick responses!

I have an express.js site and I want to load stockfish in a worker thread.

I've seen [the demo repo](https://github.com/hi-ogawa/stockfish-nnue-wasm-demo) and I wanted to recreate it in my site.

Initially, I just tried copying over the stockfish*.js (and wasm) files to my public folder and adding a stockfish.js script tag.
Then running something like the following from the web console:
```js
Stockfish().then(sf => {window.stockfish = sf;}).catch(f => {console.log(f);});}
```

This works on the [demo site](https://github.com/hi-ogawa/stockfish-nnue-wasm-demo), but on my express site it produces the following error:
```
pthread sent an error! undefined:undefined: undefined
```

I'm not sure where to start poking to debug it.

Any help would be appreciated.

Keep doing cool stuff!
Uri

**Comment by hyperfoo** [comment]
OK :)! I think I solved it :).

To solve the CORS issues, you need to [set certain headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy).

I actually set those headers, but I needed to set the headers before handing the http calls to the static files I was serving. So the code should look something like this:
```js
// This needs to appear before the express.static call!!!
app.use(function(req, res, next) {
  /// Firefox needs these headers in order to handle shared array buffers for multi-threaded WASM.
  res.header("Cross-Origin-Embedder-Policy", "require-corp");
  res.header("Cross-Origin-Opener-Policy", "same-origin");
  next();
});

app.use(express.static('public'))
```

Two things I still wonder about:
 1. I wonder if the library can produce a more helpful error message...
 1. And I'd love to better understand the difference between including stockfish.js as a script and somehow creating a worker thread directly.

**Comment by shuri** [comment]
OK :)! I think I solved it :).

To solve the CORS issues, you need to [set certain headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy).

I actually set those headers, but I needed to set the headers before handing the http calls to the static files I was serving. So the code should look something like this:
```js
// This needs to appear before the express.static call!!!
app.use(function(req, res, next) {
  /// Firefox needs these headers in order to handle shared array buffers for multi-threaded WASM.
  res.header("Cross-Origin-Embedder-Policy", "require-corp");
  res.header("Cross-Origin-Opener-Policy", "same-origin");
  next();
});

app.use(express.static('public'))
```

Two things I still wonder about:
 1. I wonder if the library can produce a more helpful error message...
 1. And I'd love to better understand the difference between including stockfish.js as a script and somehow creating a worker thread directly.

Thanks for the help!
Uri
