### ISSUE TITLE
is there any way to separate the nnue data from the wasm binary?

### ISSUE THREAD

**Issue by gmcheems** [hi-ogawa/Stockfish#3]
I'm not 100% familiar with how this works but is the wasm file huge because it packs in the NNUE data? If so can we separate the NNUE data from everything else, and download it separately? That way we can load and unload different datasets.
thamks

**Comment by hi-ogawa** [comment]
> is the wasm file huge because it packs in the NNUE data?

Yes, that's correct. About 20MB of NNUE weight data is embedded in wasm binary itself (I think official stockfish also distributes it in this way, at least on Linux?).
But if you serve "stockfish.wasm" file with standard gzip-like compression on the web, usually it can get to about 10MB.

> can we separate the NNUE data from everything else, and download it separately?

Currently my port doesn't support such usage (essentially `setoption name EvalFile ...` doesn't do anything). But technically it should be possible to implement such feature with emscripten. I would welcome PR but don't plan to do it myself yet.

**Comment by hi-ogawa** [comment]
I'll close this for inactivity, but this will be possible in a new version. See here for the detail https://github.com/hi-ogawa/Stockfish/issues/9.
